# $@ = target file
# $< = first dependency
# $^ = all dependencies

# First rule is the one executed when no parameters are given to the MakeFile
all: run

# All dependencies are built as you need them
kernel.bin: kernel_entry.o kernel.o
	i386-elf-ld -o $@ -Ttext 0x1000 $^ --oformat binary

kernel_entry.o: kernel_entry.asm
	nasm $< -f elf -o $@

kernel.o: kernel.c
	i386-elf-ld -o $@

# Rule to disasseble the kernel - may be useful for debugging
kernel.dis: kernel.bin
	ndisasm -b 32 $< > $@

bootsect.bin: bootsect.asm 
	nasm $< -f bin -o $@

os-image-bin: bootsect.bin kernel.bin
	cat $^ > $@

run: os-image.bin
	qemu-system-i386 -fda $<

clean:
	rm *.bin *.o *.dis
